title: Yihui 'Alex' Wei's Homepage
email: yihui.w@columbia.edu
description: "This is a personal website for professional purposes"
baseurl: ""
url: "https://yhuiw.github.io"
github_username: yhuiw
linkedin_username: yihuiwei

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
